const login=document.getElementById('login'),editor=document.getElementById('editor'),status=document.getElementById('saveStatus');
const imageTargets=[['hero','Hero image','images/hero.jpg'],['about','Methodology image','images/about.jpg'],['course','Closing image','images/course.jpg'],['logo','Logo image','images/logo.jpg']];
let content=null;
const API_BASE='https://static.casamigo.net/oceanicvibes-api';
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||'Request failed');return data}
function setStatus(message,error=false){status.textContent=message;status.classList.toggle('error',error)}
async function loadContent(){content=await api('/api/content');populate();renderImages()}
function showEditor(){login.hidden=true;editor.hidden=false;loadContent().catch(error=>setStatus(error.message,true))}
document.querySelector('.admin-header .intro').textContent='Update website content and replace images. Publish changes directly to GitHub from this secure local admin server.';
document.querySelector('.login-panel small').textContent='Your password is checked by the VPS admin server. GitHub credentials stay on the server and are never sent to the browser.';
document.getElementById('loginForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify({password:document.getElementById('password').value})});showEditor()}catch{document.getElementById('loginError').hidden=false}});
document.getElementById('logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});
function populate(){const form=document.getElementById('contentForm');Object.entries(content).forEach(([key,value])=>{if(key!=='courses'&&form.elements[key])form.elements[key].value=value});renderCourses()}
function renderCourses(){document.getElementById('courseFields').innerHTML=content.courses.map((course,index)=>`<div class="course-editor" data-index="${index}"><label>Date range<input data-key="date" value="${escapeAttr(course.date)}"></label><label>Location<select data-key="location"><option ${course.location==='Playa del Carmen'?'selected':''}>Playa del Carmen</option><option ${course.location==='Bacalar'?'selected':''}>Bacalar</option></select></label><button type="button" class="remove-course" aria-label="Remove session">×</button><label class="description">Session title<input data-key="title" value="${escapeAttr(course.title)}"></label><label class="description">Description<textarea data-key="description" rows="3">${escapeHtml(course.description)}</textarea></label></div>`).join('');document.querySelectorAll('.course-editor [data-key]').forEach(input=>input.addEventListener('input',event=>{content.courses[Number(event.target.closest('.course-editor').dataset.index)][event.target.dataset.key]=event.target.value}));document.querySelectorAll('.remove-course').forEach(button=>button.addEventListener('click',event=>{content.courses.splice(Number(event.target.closest('.course-editor').dataset.index),1);renderCourses()}))}
document.getElementById('addCourse').addEventListener('click',()=>{content.courses.push({date:'New date',location:'Playa del Carmen',title:'New training session',description:'Describe what students will learn in this session.'});renderCourses()});
document.getElementById('contentForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);Object.keys(content).filter(key=>key!=='courses').forEach(key=>content[key]=form.get(key));try{await api('/api/content',{method:'PUT',body:JSON.stringify(content)});setStatus('Published content to GitHub')}catch(error){setStatus(error.message,true)}});
function renderImages(){const panel=document.getElementById('imageManager');if(panel)return;const section=document.createElement('section');section.id='imageManager';section.className='panel image-manager';section.innerHTML=`<p class="eyebrow">03 / Site imagery</p><h2>Replace the water.</h2><p class="image-manager-intro">These are the current images from the website. Choose a replacement, preview it, and publish it directly to GitHub.</p><div class="image-grid">${imageTargets.map(([key,label,path])=>`<article class="image-editor"><div class="image-preview"><img src="/${path}?v=${Date.now()}" alt="Current ${label.toLowerCase()}"><span class="image-upload-preview" data-preview="${key}" hidden></span></div><div class="image-editor-copy"><strong>${label}</strong><code>${path}</code><label class="image-picker">Choose replacement<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" data-image="${key}"></label><button type="button" class="secondary image-publish" data-publish="${key}" disabled>Publish to GitHub</button><small data-image-status="${key}">Current image shown above.</small></div></article>`).join('')}</div>`;editor.insertBefore(section,document.getElementById('contentForm'));document.querySelectorAll('[data-image]').forEach(input=>input.addEventListener('change',previewImage));document.querySelectorAll('[data-publish]').forEach(button=>button.addEventListener('click',publishImage))}
const imageFiles={};function previewImage(event){const file=event.target.files[0];if(!file)return;const key=event.target.dataset.image;imageFiles[key]=file;const preview=document.querySelector(`[data-preview="${key}"]`);preview.hidden=false;preview.innerHTML='';const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt='Selected replacement';preview.appendChild(image);document.querySelector(`[data-publish="${key}"]`).disabled=false;document.querySelector(`[data-image-status="${key}"]`).textContent=`Ready to publish: ${file.name}`}
async function publishImage(event){const key=event.target.dataset.publish,file=imageFiles[key];if(!file)return;const button=event.target;button.disabled=true;document.querySelector(`[data-image-status="${key}"]`).textContent='Publishing...';try{const data=await fileAsDataUrl(file);const result=await api(`/api/images/${key}`,{method:'PUT',body:JSON.stringify({data})});document.querySelector(`[data-image-status="${key}"]`).textContent=`Published ${result.path}; Pages will rebuild shortly`;document.querySelector(`[data-publish="${key}"]`).textContent='Published'}catch(error){button.disabled=false;document.querySelector(`[data-image-status="${key}"]`).textContent=error.message;setStatus(error.message,true)}}
function fileAsDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function escapeAttr(value){return String(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function escapeHtml(value){return escapeAttr(value).replace(/\n/g,'&#10;')}
api('/api/session').then(session=>{if(session.authenticated)showEditor()}).catch(()=>{});
