const PASSWORD='oceanic2026';
const defaults={heroEyebrow:'Riviera Maya · Mexico',heroTitle:'Master|your depth.',heroSubtitle:'Elite freediving instruction, advanced equalization, and depth training for people who want to feel at home beneath the surface.',aboutLead:'At OceanicVibes, we train athletes, watermen, and dedicated individuals to safely unlock their true aquatic potential.',aboutBody:'From Frenzel and Mouthfill equalization to CO2 tolerance and deep relaxation, every session is built around calm, measurable progression and uncompromising safety.',footerCopy:'Private instruction and depth training in the waters of the Yucatan.',footerEmail:'train@oceanicvibes.com',instagram:'@oceanic__vibesfreediving',courses:[{date:'Oct 15–17',location:'Playa del Carmen',title:'AIDA 2 Foundation',description:'Build a bulletproof foundation with Frenzel equalization, duck dives, breathing techniques, and safety protocols up to 20 meters.'},{date:'Nov 02–05',location:'Bacalar',title:'Stillness & Technique',description:'A focused Bacalar weekend for breathwork, relaxation, body position, and the calm precision that makes depth feel effortless.'},{date:'Nov 18–22',location:'Playa del Carmen',title:'Advanced Depth',description:'Line training in Free Immersion and Constant Weight, with advanced equalization and coaching through your next depth barrier.'}]};
let content=defaults;const login=document.getElementById('login'),editor=document.getElementById('editor');
fetch('content.json',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then(value=>{content=value;if(!editor.hidden)populate()}).catch(()=>{});
function showEditor(){login.hidden=true;editor.hidden=false;populate()}if(sessionStorage.getItem('oceanicAdmin')==='yes')showEditor();
document.getElementById('loginForm').addEventListener('submit',event=>{event.preventDefault();if(document.getElementById('password').value===PASSWORD){sessionStorage.setItem('oceanicAdmin','yes');showEditor()}else document.getElementById('loginError').hidden=false});document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem('oceanicAdmin');location.reload()});
function populate(){const form=document.getElementById('contentForm');Object.entries(content).forEach(([key,value])=>{if(key!=='courses'&&form.elements[key])form.elements[key].value=value});renderCourses()}
function renderCourses(){document.getElementById('courseFields').innerHTML=content.courses.map((course,index)=>`<div class="course-editor" data-index="${index}"><label>Date range<input data-key="date" value="${escapeAttr(course.date)}"></label><label>Location<select data-key="location"><option ${course.location==='Playa del Carmen'?'selected':''}>Playa del Carmen</option><option ${course.location==='Bacalar'?'selected':''}>Bacalar</option></select></label><button type="button" class="remove-course" aria-label="Remove session">×</button><label class="description">Session title<input data-key="title" value="${escapeAttr(course.title)}"></label><label class="description">Description<textarea data-key="description" rows="3">${escapeHtml(course.description)}</textarea></label></div>`).join('');document.querySelectorAll('.course-editor [data-key]').forEach(input=>input.addEventListener('input',event=>{content.courses[Number(event.target.closest('.course-editor').dataset.index)][event.target.dataset.key]=event.target.value}));document.querySelectorAll('.remove-course').forEach(button=>button.addEventListener('click',event=>{content.courses.splice(Number(event.target.closest('.course-editor').dataset.index),1);renderCourses()}))}
document.getElementById('addCourse').addEventListener('click',()=>{content.courses.push({date:'New date',location:'Playa del Carmen',title:'New training session',description:'Describe what students will learn in this session.'});renderCourses()});
document.getElementById('contentForm').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);Object.keys(defaults).filter(key=>key!=='courses').forEach(key=>content[key]=form.get(key));downloadContent();document.getElementById('saveStatus').textContent='Downloaded content.json; commit it to GitHub'});
document.getElementById('download').addEventListener('click',downloadContent);function downloadContent(){const blob=new Blob([JSON.stringify(content,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='content.json';link.click();URL.revokeObjectURL(link.href)}
document.getElementById('upload').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{content=JSON.parse(reader.result);populate();document.getElementById('saveStatus').textContent='Content loaded'}catch{alert('That content file could not be read.')}};reader.readAsText(file)});
function escapeAttr(value){return String(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function escapeHtml(value){return escapeAttr(value).replace(/\n/g,'&#10;')}

const imageTargets=[['hero','Hero image','images/hero.jpg'],['about','Methodology image','images/about.jpg'],['course','Closing image','images/course.jpg'],['logo','Logo image','images/logo.jpg']];
const imagePanel=document.createElement('section');imagePanel.className='panel image-manager';imagePanel.innerHTML=`<p class="eyebrow">03 / Site imagery</p><h2>Replace the water.</h2><p class="image-manager-intro">Choose a replacement, preview it, then download the file. Replace the matching file in the repository and commit it to GitHub.</p><div class="image-grid">${imageTargets.map(([key,label,path])=>`<article class="image-editor"><div class="image-preview" data-preview="${key}"><span>No image selected</span></div><div class="image-editor-copy"><strong>${label}</strong><code>${path}</code><label class="image-picker">Choose image<input type="file" accept="image/*" data-image="${key}"></label><button type="button" class="secondary image-download" data-download="${key}" disabled>Download ${key}.jpg</button><small data-image-status="${key}">Choose an image to enable download.</small></div></article>`).join('')}</div>`;
document.getElementById('editor').insertBefore(imagePanel,document.getElementById('contentForm'));const imageFiles={};document.querySelectorAll('[data-image]').forEach(input=>input.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const key=event.target.dataset.image;imageFiles[key]=file;const preview=document.querySelector(`[data-preview="${key}"]`);preview.innerHTML='';const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt='Selected replacement';preview.appendChild(image);document.querySelector(`[data-download="${key}"]`).disabled=false;document.querySelector(`[data-image-status="${key}"]`).textContent=`Ready: ${file.name}`}));document.querySelectorAll('[data-download]').forEach(button=>button.addEventListener('click',event=>{const key=event.target.dataset.download,file=imageFiles[key];if(!file)return;const target=imageTargets.find(item=>item[0]===key);const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=target[2].split('/').pop();link.click();URL.revokeObjectURL(link.href);document.querySelector(`[data-image-status="${key}"]`).textContent=`Downloaded ${target[2]}; replace it in GitHub`;}));
